FROM php:8.3-cli

RUN apt-get update && \
    apt-get install -y unzip git zip libzip-dev libicu-dev libonig-dev libxml2-dev \
    && docker-php-ext-install pdo pdo_mysql intl zip opcache

COPY . /app
WORKDIR /app

RUN curl -sS https://getcomposer.org/installer | php && \
    php composer.phar install